# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b96427cebe2e5cc83bac612ae95a8a1c6d8394391abf5eda1ff3c47c4a415e23a96a3c782d65016814c555f40250e1d78229c8a0aa1164dee8a2698e5ead73

test:
  secret_key_base: f00e08d5739b4c62a240dfe10d5b4b438c1abfdc0c05cbfc627159fe55c297908614f9a0c536488f959fceb4169bce401b6b154702f498dc76dd8a4d5c74d5e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
